### ISSUE TITLE
DEV: 3 tests fail because of version mismatch since the version string was increased from 16.0.3 to 17.0.0

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1019]
We need to remove generated_by field to prevent mismatch in some input files.

E.g. cherry pick this commit: https://github.com/nextstrain/augur/pull/1018/commits/0f84bd922f0319e62367ad95d3f3f263554f798b

Log with bug:
```
Running functional tests with cram
..............!
--- tests/functional/translate/cram/translate-with-genbank.t
+++ tests/functional/translate/cram/translate-with-genbank.t.err
@@ -11,8 +11,12 @@
   >   --reference-sequence translate/data/zika/zika_outgroup.gb \
   >   --genes CA PRO \
   >   --output-node-data $TMP/aa_muts.json
+  ERROR: Augur version incompatibility detected: the JSON translate/data/zika/nt_muts.json was generated by {'program': 'augur', 'version': '16.0.3'}, which is incompatible with the current augur version (17.0.0). We suggest you rerun the pipeline using the current version of augur.
   Validating schema of 'translate/data/zika/nt_muts.json'...
-  Read in 3 features from reference sequence file
-  amino acid mutations written to .* (re)
+  [2]
   $ python3 "../../scripts/diff_jsons.py" translate/data/zika/aa_muts_genbank.json $TMP/aa_muts.json
-  {}
+  Traceback (most recent call last):
+    File "/Users/cr/code/augur/tests/functional/../../scripts/diff_jsons.py", line 24, in <module>
+      with open(args.second_json, "r") as fh:
+  FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1n/22rjr5g11cxf3zgt_zfn4v3r0000gn/T/cramtests-ct0_xk2_/tmp/aa_muts.json'
+  [1]
!
--- tests/functional/translate/cram/translate-with-gff-and-gene-name.t
+++ tests/functional/translate/cram/translate-with-gff-and-gene-name.t.err
@@ -17,9 +17,9 @@
   >   --ancestral-sequences translate/data/zika/nt_muts.json \
   >   --reference-sequence "$TMP/genemap.gff" \
   >   --output-node-data $TMP/aa_muts.json
+  ERROR: Augur version incompatibility detected: the JSON translate/data/zika/nt_muts.json was generated by {'program': 'augur', 'version': '16.0.3'}, which is incompatible with the current augur version (17.0.0). We suggest you rerun the pipeline using the current version of augur.
   Validating schema of 'translate/data/zika/nt_muts.json'...
-  Read in 2 features from reference sequence file
-  amino acid mutations written to .* (re)
+  [2]
 
 Other than the sequence ids which will include a temporary path, the JSONs
 should be identical.
@@ -28,4 +28,8 @@
   >  --exclude-regex-paths "['seqid']" -- \
   >  translate/data/zika/aa_muts_gff.json \
   >  $TMP/aa_muts.json
-  {}
+  Traceback (most recent call last):
+    File "/Users/cr/code/augur/tests/functional/../../scripts/diff_jsons.py", line 24, in <module>
+      with open(args.second_json, "r") as fh:
+  FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1n/22rjr5g11cxf3zgt_zfn4v3r0000gn/T/cramtests-ct0_xk2_/tmp/aa_muts.json'
+  [1]
!
--- tests/functional/translate/cram/translate-with-gff-and-gene.t
+++ tests/functional/translate/cram/translate-with-gff-and-gene.t.err
@@ -17,11 +17,15 @@
   >   --ancestral-sequences translate/data/zika/nt_muts.json \
   >   --reference-sequence "$TMP/genemap.gff" \
   >   --output-node-data $TMP/aa_muts.json
+  ERROR: Augur version incompatibility detected: the JSON translate/data/zika/nt_muts.json was generated by {'program': 'augur', 'version': '16.0.3'}, which is incompatible with the current augur version (17.0.0). We suggest you rerun the pipeline using the current version of augur.
   Validating schema of 'translate/data/zika/nt_muts.json'...
-  Read in 2 features from reference sequence file
-  amino acid mutations written to .* (re)
+  [2]
   $ python3 "../../scripts/diff_jsons.py" \
   >  --exclude-regex-paths "['seqid']" -- \
   >  translate/data/zika/aa_muts_gff.json \
   >  $TMP/aa_muts.json
-  {}
+  Traceback (most recent call last):
+    File "/Users/cr/code/augur/tests/functional/../../scripts/diff_jsons.py", line 24, in <module>
+      with open(args.second_json, "r") as fh:
+  FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1n/22rjr5g11cxf3zgt_zfn4v3r0000gn/T/cramtests-ct0_xk2_/tmp/aa_muts.json'
+  [1]
...............................
# Ran 48 tests, 0 skipped, 3 failed.
```

**Comment by huddlej** [comment]
Thank you for catching this, @corneliusroemer, and fixing it, @victorlin. This major version error is so much more annoying than I can imagine it being helpful. I understand how this check seemed important when we only made major version releases once a year (esp. from v5 to v6) with major backwards-incompatible changes, but now it feels like more of a headache than it is worth.

**Comment by corneliusroemer** [comment]
Yeah, I've run into this quite a bit.

We could consider phasing the errors out and put warnings there instead? Or
scrap it altogether.
