### ISSUE TITLE
ENH(parse): Support gz/xz/zstd compressed sequences/metadata for IO and/or output to stdout (to allow compression in pipe)

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1221]
### Context
Just trying out `parse` for the first time. Noticed that compressed sequence in/out does not seem to be supported. Would be nice to reduce storage usage and speed things up.

Related to #1219 

Also, if you pass a compressed file you get an improperly caught error:

```log
augur parse --sequences data/gisaid.fasta.gz --output-sequences data/gisaid_parsed.fasta.gz
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/augur/parse.py", line 165, in run
    if 'name' in args.fields:
TypeError: argument of type 'NoneType' is not iterable


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

**Comment by corneliusroemer** [comment]
Current workaround (quite sufficient I think):

```bash
zstdcat data/gisaid.fasta.zst |  augur parse --sequences /dev/stdin  --output-sequences /dev/stdout --fields strain --output-metadata test.tsv | zstd > data/gisaid_parsed.fasta.zst 
```
