### ISSUE TITLE
filter: Improperly handled `ValueError: not enough values to unpack (expected 2, got 1)` in ` _parse_filter_query`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1230]
### Current Behavior
I get an error that's not very helpful:

```
        augur filter             --sequences data/sequences.fasta.zst             --metadata results/metadata.tsv             --exclude config/exclude_accessions_mpxv.txt             --output-sequences results/hmpxv1/good_sequences.fasta.zst             --output-metadata results/hmpxv1/good_metadata.tsv             --min-date 2017             --min-length 180000             --exclude-where outbreak!=hMPXV-1 "coverage<0.95" "divergence<550" "missing_data>10000" "divergence>650" QC_rare_mutations!=good             --output-log results/hmpxv1/good_filter.log
        
Note: You did not provide a sequence index, so Augur will generate one. You can generate your own index ahead of time with `augur index` and pass it with `augur filter --sequence-index`.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/filter/__init__.py", line 97, in run
    return _run(args)
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/filter/_run.py", line 192, in run
    seq_keep, sequences_to_filter, sequences_to_include = apply_filters(
                                                          ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/filter/include_exclude_rules.py", line 707, in apply_filters
    passed = metadata.pipe(
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/core/generic.py", line 5839, in pipe
    return com.pipe(self, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/core/common.py", line 513, in pipe
    return func(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/filter/include_exclude_rules.py", line 139, in filter_by_exclude_where
    column, op, value = _parse_filter_query(exclude_where)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/augur/filter/include_exclude_rules.py", line 100, in _parse_filter_query
    column, value = re.split(r'!?=', query)
    ^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```
### Expected behavior

Error is properly handled and error message tells me how to fix

### System

Augur 22.0.1, Python 3.11 on ARM (!) macOS

**Comment by ammaraziz** [comment]
I also hit this issue. I wanted to point out that the syntax is slightly different between `--query` and `--exclude` which adds some confusion:

Exclude requires single `=`
```
--exclude-where EXCLUDE_WHERE [EXCLUDE_WHERE ...]
                        Exclude samples matching these conditions. Ex: "host=rat" or
                        "host!=rat". Multiple values are processed as OR (matching any of
                        those specified will be excluded), not AND (default: None)
```

while query requires double `==`:
```
  --query QUERY         Filter samples by attribute. Uses Pandas Dataframe querying, see
                        https://pandas.pydata.org/pandas-
                        docs/stable/user_guide/indexing.html#indexing-query for syntax.
                        (e.g., --query "country == 'Colombia'" or --query "(country == 'USA'
                        & (division == 'Washington'))") (default: None)
```

I think the syntax needs to be the same.
