### ISSUE TITLE
Metadata reader doesn't handle parsing errors: `pandas.errors.ParserError: Error tokenizing data. C error: Expected 57 fields in line 502, saw 58`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1307]
### Current Behavior
Metadata parsing error from pandas are currently unhandled. We should at least catch it and wrap it in something that pinpoints which file is at fault here.

### Expected behavior
Errors are handled and helpful message printed to user

### How to reproduce
Steps to reproduce the current behavior:
1. Create a metadata.tsv with different numbers of columns
2. Run 
```
augur filter       --sequences builds/sequences_sample.fasta             --metadata builds/metadata_sample.tsv             --exclude config/exclude.txt   --output builds/sequences.fasta
```
4. See error:
```bash
$ augur filter             --sequences builds/sequences_sample.fasta             --metadata builds/metadata_sample.tsv             --exclude config/exclude.txt             --output builds/sequences.fasta
            --output-metadata builds/metadata.tsv
        
Note: You did not provide a sequence index, so Augur will generate one. You can generate your own index ahead of time with `augur index` and pass it with `augur filter --sequence-index`.
Traceback (most recent call last):
  File "/Users/corneliusromer/code/augur/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/corneliusromer/code/augur/augur/filter/__init__.py", line 97, in run
    return _run(args)
           ^^^^^^^^^^
  File "/Users/corneliusromer/code/augur/augur/filter/_run.py", line 179, in run
    for metadata in metadata_reader:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1698, in __next__
    return self.get_chunk()
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1810, in get_chunk
    return self.read(nrows=size)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py11/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 235, in read
    data = self._reader.read(nrows)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 790, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 57 fields in line 502, saw 58


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

### Possible solution

Maybe we could also use `on_bad_lines` for this to report more specifically what the bad line is:
<img width="712" alt="image" src="https://github.com/nextstrain/augur/assets/25161793/a2788362-925b-44cf-965a-54f568c7e10c">
https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.read_csv.html

### Your environment: if running Nextstrain locally
macOS 13.5.1 (ARM): 22.3.0

**Comment by victorlin** [comment]
This is pretty much #1195 but the mismatch is happening while using the chunk iterator, rather than inside `read_metadata`.
