### ISSUE TITLE
ancestral, translate: GFF parsing broken with Biopython >=1.82

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#1373]
## Scope

- When VCF is used in `augur translate --alignment`
- All usage of `augur translate`

## Details

[Biopython 1.82](https://github.com/biopython/biopython/blob/biopython-182/NEWS.rst) was released a few hours ago which removed a [deprecated](https://github.com/biopython/biopython/blob/15dcc258a2941910fcedcb641777d2c15244d1cb/DEPRECATED.rst#bioseqfeature) feature in the `SeqFeature` API which is used indirectly in Augur through another dependency, BCBio ([upstream issue](https://github.com/chapmanb/bcbb/issues/138)). See [failing CI](https://github.com/nextstrain/augur/actions/runs/7302519040/job/19901294904) for details.

Error message for search-ability:

```
Traceback (most recent call last):
  File "/home/runner/work/augur/augur/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/home/runner/work/augur/augur/augur/translate.py", line 405, in run
    features = load_features(args.reference_sequence, genes)
  File "/home/runner/work/augur/augur/augur/utils.py", line 174, in load_features
    return _read_gff(reference, feature_names)
  File "/home/runner/work/augur/augur/augur/utils.py", line 277, in _read_gff
    gff_entries = list(GFF.parse(in_handle, limit_info={'gff_type': valid_types}))
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 793, in parse
    for rec in parser.parse_in_parts(gff_files, base_dict, limit_info,
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 337, in parse_in_parts
    cur_dict = self._results_to_features(cur_dict, results)
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 376, in _results_to_features
    base = self._add_parent_child_features(base, results.get('parent', []),
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 462, in _add_parent_child_features
    cur_parent, base = self._add_toplevel_feature(base, cur_parent_dict)
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 582, in _add_toplevel_feature
    new_feature = self._get_feature(feature_dict)
  File "/home/runner/miniconda3/envs/test/lib/python3.10/site-packages/BCBio/GFF/GFFParser.py", line 591, in _get_feature
    new_feature = SeqFeature.SeqFeature(location, feature_dict['type'],
TypeError: SeqFeature.__init__() got an unexpected keyword argument 'strand'


An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

## Possible solutions

_In the meantime, users should downgrade to an earlier version of Biopython._

- Short-term: [mark 1.82 as unsupported](https://github.com/nextstrain/augur/pull/1374)
    - Instead of releasing a major version of Augur, apply this to Nextstrain's managed runtimes.
- Long-term: Submit a patch to bcbio-gff and hope it gets released.

**Comment by victorlin** [comment]
There is also usage of the deprecated feature within Augur itself:

https://github.com/nextstrain/augur/blob/ad4ed1baee2b6a10f794a484f721b2c94320e122/augur/utils.py#L210-L212

Currently looking into why Biopython's deprecation warning doesn't get surfaced when using Augur CLI.
