### ISSUE TITLE
frequencies: UnboundLocalError: local variable 'weights_attribute' referenced before assignment

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1412]
Error seen in [private seasonal flu build](https://github.com/nextstrain/seasonal-flu/actions/runs/7893249149). 

```
[batch] [2024-02-13T14:17:13-08:00] Traceback (most recent call last):
[batch] [2024-02-13T14:17:13-08:00]   File "/nextstrain/augur/augur/__init__.py", line 66, in run
[batch] [2024-02-13T14:17:13-08:00]     return args.__command__.run(args)
[batch] [2024-02-13T14:17:13-08:00]   File "/nextstrain/augur/augur/frequencies.py", line 129, in run
[batch] [2024-02-13T14:17:13-08:00]     if weights_attribute:
[batch] [2024-02-13T14:17:13-08:00] UnboundLocalError: local variable 'weights_attribute' referenced before assignment
[batch] [2024-02-13T14:17:13-08:00] An error occurred (see above) that has not been properly handled by Augur.
[batch] [2024-02-13T14:17:13-08:00] To report this, please open a new issue including the original command and the error above:
[batch] [2024-02-13T14:17:13-08:00]     <https://github.com/nextstrain/augur/issues/new/choose>
```

**Comment by victorlin** [comment]
This happens when `--method diffusion` is used with `--weights-attribute`. Will make a PR to fix.

**Comment by victorlin** [comment]
Pyright (#1246) has the ability to catch these types of programming errors in CI.
