### ISSUE TITLE
frequencies: error with `--region` flag 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/augur#1423]
This bug initially discovered in the [private seasonal flu workflow](https://github.com/nextstrain/seasonal-flu/actions/runs/8012696371). 

Use of the `--region` flag results in the following error:
```
[batch] [2024-02-22T16:28:59-08:00] Traceback (most recent call last):
[batch] [2024-02-22T16:28:59-08:00]   File "/nextstrain/augur/augur/__init__.py", line 66, in run
[batch] [2024-02-22T16:28:59-08:00]     return args.__command__.run(args)
[batch] [2024-02-22T16:28:59-08:00]   File "/nextstrain/augur/augur/frequencies.py", line 148, in run
[batch] [2024-02-22T16:28:59-08:00]     tree_freqs = tree_frequencies(tree, pivots, method='SLSQP',
[batch] [2024-02-22T16:28:59-08:00]   File "/nextstrain/augur/augur/frequency_estimators.py", line 502, in __init__
[batch] [2024-02-22T16:28:59-08:00]     self.prepare()
[batch] [2024-02-22T16:28:59-08:00]   File "/nextstrain/augur/augur/frequency_estimators.py", line 516, in prepare
[batch] [2024-02-22T16:28:59-08:00]     if self.node_filter(node):
[batch] [2024-02-22T16:28:59-08:00]   File "/nextstrain/augur/augur/frequencies.py", line 145, in <lambda>
[batch] [2024-02-22T16:28:59-08:00]     node_filter_func = lambda node: (node.attr["region"] == region
[batch] [2024-02-22T16:28:59-08:00] KeyError: 'region'
[batch] [2024-02-22T16:28:59-08:00] An error occurred (see above) that has not been properly handled by Augur.
[batch] [2024-02-22T16:28:59-08:00] To report this, please open a new issue including the original command and the error above:
[batch] [2024-02-22T16:28:59-08:00]     <https://github.com/nextstrain/augur/issues/new/choose>
```

**Comment by joverlee521** [comment]
Hmm, most likely a result of the change to read a subset of metadata columns in https://github.com/nextstrain/augur/pull/1294

**Comment by joverlee521** [comment]
Errors for any regions that are not `global` because it requires the `region` metadata field:

https://github.com/nextstrain/augur/blob/f81e6a319f74c812703ffdf1f93ae9ef27d1d54d/augur/frequencies.py#L139-L146

**Comment by joverlee521** [comment]
Ah, also because we changed to only annotating tips with `weight_attributes` in https://github.com/nextstrain/augur/pull/1398/commits/dde857a23dffdfa9d841ae8d245d77194bd741de
