### ISSUE TITLE
Augur export error

### ISSUE THREAD

**Issue by fiiiibiiiii** [nextstrain/augur#1461]
### Current Behavior
(base) nicole@Nics:~/Nextstrain$ augur export v2 \
  --tree tree.nwk \
  --metadata metadata_allseq.tsv \
  --node-data branch_lengths.json \
              traits.json \
              nt_muts.json \
              aa_muts.json \
  --output rabv.json
DEPRECATED: Accessing Draft6Validator.resolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization.

Validating schema of 'nt_muts.json'...
Validating schema of 'aa_muts.json'...
WARNING: You didn't provide information on who is maintaining this analysis.

Validating produced JSON
DEPRECATED: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.

DEPRECATED: Accessing Draft6Validator.resolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization.

Validating schema of 'rabv.json'...
Traceback (most recent call last):
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 1175, in resolve_fragment
    document = document[part]
KeyError: 'tree'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/augur/export_v2.py", line 1253, in run
    validate_data_json(args.output, args.validation_mode)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/augur/export_v2.py", line 552, in validate_data_json
    validate_v2(main_json=filename)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/augur/validate.py", line 207, in export_v2
    validate(main, main_schema, main_json)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/augur/validate.py", line 87, in validate_json
    errors = list(schema.iter_errors(jsonToValidate))
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 384, in iter_errors
    for error in errors:
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/_keywords.py", line 296, in properties
    yield from validator.descend(
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/_keywords.py", line 355, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/_keywords.py", line 275, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 478, in _validate_reference
    scope, resolved = resolve(ref)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 1108, in resolve
    return url, self._remote_cache(url)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 1126, in resolve_from_url
    return self.resolve_fragment(document, fragment)
  File "/home/nicole/anaconda3/lib/python3.9/site-packages/jsonschema/validators.py", line 1177, in resolve_fragment
    raise exceptions._RefResolutionError(
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: '$defs/tree'

### Expected behavior
json file of phylodynamics from --tree schema should be produced
3.

**Comment by victorlin** [comment]
Hi @fiiiibiiiii, this error is due to #1358. Can you try one of the workarounds in that issue description and let me know if it works?
