### ISSUE TITLE
augur filter unhelpful error message

### ISSUE THREAD

**Issue by gboyle2** [nextstrain/augur#261]
Running `augur filter` without an `--exclude`  command as in:

```
augur filter \
  --sequences ../influenza-ha/data/corrected.fasta \
  --metadata ../influenza-ha/data/metadata.tsv \
  --output ../influenza-ha/results/filtered.fasta 
```

yields error message:

> 

Traceback (most recent call last):
  File "/home/gboyle/.local/bin//augur", line 11, in <module>
    sys.exit(main())
  File "/home/gboyle/.local/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/gboyle/.local/lib/python3.6/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/home/gboyle/.local/lib/python3.6/site-packages/augur/filter.py", line 293, in run
    SeqIO.write(seq_to_keep, args.output, 'fasta')
  File "/home/gboyle/.local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 529, in write
    fp.write(format_function(record))
AttributeError: 'NoneType' object has no attribute 'write'

> 

Message "AttributeError: 'NoneType' object has no attribute 'write'" was unhelpful in troubleshooting the issue. The issue was resolved when I included an `--exclude None` command as follows:

```
augur filter \
  --sequences ../influenza-ha/data/corrected.fasta \
  --metadata ../influenza-ha/data/metadata.tsv \
  --exclude None \
  --output ../influenza-ha/results/filtered.fasta
```

**Comment by trvrb** [comment]
Thanks for the bug report @gboyle2! Your initial example (without `--exclude`) should indeed work. We'll fix this.
