### ISSUE TITLE
Calling augur titers with no valid titers breaks builds.

### ISSUE THREAD

**Issue by barneypotter24** [nextstrain/augur#279]
Running a seasonal flu build will break if there are no valid titers in the specified titer input file. This comes up in the most recent NIID 2y H3N2 HI builds, as the HI assay has now been replaced with FRA assays for over 2 years. This error comes up both on AWS and locally when the `seasonal-flu` script `batch.py` is invoked:

```
python batch.py -v who --system local -l h3n2 -r 2y -a hi -c niid
```
Note that this call to `batch.py` will download the relevant input files necessary to re-create the error.
This yields the following error message either locally or on [AWS](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=nextstrain-job/default/8e907abb-36cf-4f3d-b006-cd48bd922287):

```
Finished job 3.
3 of 13 steps (23%) done

rule titers_tree:
    input: data/niid_h3n2_cell_hi_titers.tsv, results/tree_niid_h3n2_ha_2y_cell_hi.nwk
    output: results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json
    jobid: 14
    wildcards: center=niid, lineage=h3n2, segment=ha, resolution=2y, passage=cell, assay=hi


        augur titers tree             --titers data/niid_h3n2_cell_hi_titers.tsv             --tree results/tree_niid_h3n2_ha_2y_cell_hi.nwk             --output results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json
        
Read titers from data/niid_h3n2_cell_hi_titers.tsv, found:
 --- 748 strains
 --- 10546 data sources
 --- 10778 total measurements
Normalized titers and restricted to measurements in list:
 - remaining data set
 --- 1  reference virues
 --- 1  sera
 --- 1  test_viruses
 --- 1  non-redundant test virus/serum pairs
Made training data as fraction 1.0 of all measurements
 - remaining data set
 --- 1  reference virues
 --- 1  sera
 --- 1  test_viruses
 --- 1  non-redundant test virus/serum pairs
 --- 1  measurements in training set
# of reference strains: 1
# of eligible branches with titer constraints 0
TreeModel: no titers in training set
Traceback (most recent call last):
  File "/usr/bin/augur", line 11, in <module>
    load_entry_point('nextstrain-augur', 'console_scripts', 'augur')()
  File "/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/nextstrain/augur/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/titers.py", line 83, in run
    TM_tree.train()
  File "/nextstrain/augur/augur/titer_model.py", line 906, in train
    self._train(**kwargs)
  File "/nextstrain/augur/augur/titer_model.py", line 438, in _train
    self.model_params = self.fit_nnl1reg()
  File "/nextstrain/augur/augur/titer_model.py", line 670, in fit_nnl1reg
    n_params = self.design_matrix.shape[1]
AttributeError: 'TreeModel' object has no attribute 'design_matrix'
    Error in rule titers_tree:
        jobid: 14
        output: results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json

RuleException:
CalledProcessError in line 441 of /nextstrain/build/Snakefile_base:
Command ' set -euo pipefail;  
        augur titers tree             --titers data/niid_h3n2_cell_hi_titers.tsv             --tree results/tree_niid_h3n2_ha_2y_cell_hi.nwk             --output results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json ' returned non-zero exit status 1.
  File "/nextstrain/build/Snakefile_base", line 441, in __rule_titers_tree
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /nextstrain/build/.snakemake/log/2019-04-30T224813.269921.snakemake.log
```

The exact same error (minus the Snakemake output) can then be re-created by calling `augur titers tree` as described in the error message:

```
augur titers tree             --titers data/niid_h3n2_cell_hi_titers.tsv             --tree results/tree_niid_h3n2_ha_2y_cell_hi.nwk             --output results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json
```

The error log indicates that this error triggers because of a lack of titers, so a potential short-term fix would be to ignore running the tree model if there are no titers available, however it is unclear to me whether this is the best long-term solution.

**Comment by huddlej** [comment]
Closed by #281
