### ISSUE TITLE
better error message for invalid config file

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#384]
Recent error report from augur 5.x (might have been an earlier version):

```
Job 1: Exporting data files for for auspice

Traceback (most recent call last):
  File "/anaconda3/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/anaconda3/lib/python3.6/site-packages/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/anaconda3/lib/python3.6/site-packages/augur/export.py", line 485, in run
    meta_json = read_config(args.auspice_config)
  File "/anaconda3/lib/python3.6/site-packages/augur/utils.py", line 221, in read_config
    config = json.load(ifile)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 14 column 5 (char 535)
```

Fixed by checking the validity of the config file.

---

Solution 1: We should catch errros such as these during parsing of the config file and print a more helpful error message.

Solution 2: In augur v6, there is a JSON schema for the config file for `augur export v2` which should be able to identify errors in the content of the file, not just JSON-syntax errors: https://github.com/nextstrain/augur/blob/v6/augur/data/schema-auspice-config-v2.json. `augur export v2` should use a JSON validator for any provided config file.

**Comment by jameshadfield** [comment]
Closed in v6 via https://github.com/nextstrain/augur/commit/dd0b26ab06e82a9c02cbc5857666b3a71769d1bf
