### ISSUE TITLE
list indices must be integers or slices, not float error

### ISSUE THREAD

**Issue by pvanheus** [nextstrain/augur#453]
When processing GISAID SARS-CoV-2 sequences, I encountered the following error:

```
Job 17: Adding internal clade labels


        augur clades --tree results/tree.nwk             --mutations results/nt_muts.json results/aa_muts.json             --clades config/clades.tsv             --output-node-data results/clades.json
        
Validating schema of 'results/aa_muts.json'...
Traceback (most recent call last):
  File "/usr/bin/augur", line 11, in <module>
    load_entry_point('nextstrain-augur', 'console_scripts', 'augur')()
  File "/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/nextstrain/augur/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/clades.py", line 211, in run
    clade_membership = assign_clades(clade_designations, all_muts, tree, ref)
  File "/nextstrain/augur/augur/clades.py", line 147, in assign_clades
    if is_node_in_clade(clade_alleles, node, ref):
  File "/nextstrain/augur/augur/clades.py", line 73, in is_node_in_clade
    state = ref[gene][pos]
TypeError: list indices must be integers or slices, not float
```

examining the value of `pos` in the relevant [line](https://github.com/nextstrain/augur/blob/master/augur/clades.py#L73) I discovered that it was `250.0`. I thus put a `pos = int(pos)` before this line, which seems to resolve the error. Is there perhaps a division somewhere that used to yield an `int` in Python 2 and now yields a `float`?

**Comment by emmahodcroft** [comment]
Can you pull the latest ncov version and run? There was an error where the clades file had spaces instead of tabs as separators and this was giving me an error this morning. It should be resolved now.

**Comment by pvanheus** [comment]
Thanks, updating to the latest `ncov` fixes this problem.
