### ISSUE TITLE
[BUG] AttributeError can be thrown by the run function in augur/traits.py

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/augur#497]
I'm running the Snakemake pipeline from the Zika demo on some data of my own. In my metadata I have a `region` column (as in the Zika dataset) but the 79 entries in the file all have the same region value (Europe).  I get the below Exception thrown on the `traits` rule (which calls `augur traits`). The 
`columns` parameter is "region country" (as for the Zika example). So I can probably fix this by adjusting that (or, looking at augur/traits.py I could remove the `--confidence` arg from the augur traits call), but the below exception should probably be caught.

```
WARNING: only one state found for discrete state reconstruction: ['Europe']
Traceback (most recent call last):
  File "/home/terry/miniconda3/envs/auspice/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/traits.py", line 176, in run
    mugration_states[node.name][column+'_confidence'] = node.__getattribute__(column+'_confidence')
AttributeError: 'Clade' object has no attribute 'region_confidence'
```

The point in `mugration_inference` where the entropy and confidence values are put on nodes is not reached `if len(unique_states)==0` because that function has already returned at that point. So maybe `mugration_inference` could add simple constants for those values or else pass something else back (the number of unique states?) to indicate the condition so the exception can be avoided.

**Comment by genehack** [comment]
Looking at the code for `augur traits`, I see that the referenced line has been replaced with:

```python
confidence = getattr(node, f"{column}_confidence", None)
if confidence is not None:
  mugration_states[node.name][f"{column}_confidence"] = confidence
```

so I believe this `AttributeError` should no longer be raised in this case. 

I'm going to close this issue out; if you're still seeing this problem, please reopen the issue, thanks!
