### ISSUE TITLE
[BUG] UTF-8 in the --augur-config file causes UnicodeDecodeError exception

### ISSUE THREAD

**Issue by terrycojones** [nextstrain/augur#498]
If the config file contains (non-ASCII) UTF-8 you get this:

```
Validating schema of 'results/aa_muts.json'...
Traceback (most recent call last):
  File "/home/terry/miniconda3/envs/auspice/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/export.py", line 22, in run
    return run_v2(args)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/export_v2.py", line 843, in run_v2
    config = get_config(args)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/export_v2.py", line 822, in get_config
    config = read_config(args.auspice_config)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/site-packages/augur/utils.py", line 365, in read_config
    config = json.load(ifile)
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/terry/miniconda3/envs/auspice/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 124: ordinal not in range(128)
```

Pull request coming up...

**Comment by ddomman** [comment]
I get this same error when running `augur traits` on my HPC. Strangely, this completes on my laptop without errors using same dataset. Both have same python and augur versions. 

On HPC:
```
$ python --version
Python 3.6.9 :: Anaconda, Inc.
$ augur --version
augur 6.4.3
```

On laptop:
```
$ python --version
Python 3.6.9 :: Anaconda, Inc.
$ augur --version
augur 6.4.3
```
