### ISSUE TITLE
possible bug using augur refine c/w treetime

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#551]
This issue describes a possible bug in how `augur refine` is calling `treetime`. I don't have the original files (yet) so cannot reproduce but am posting now in case we've seen this before and it's an easy solution. I'll update with further information as I get it

The following treetime command works:
```
treetime --tree <TREE> --aln <ALN> --covariation --clock-filter 0 \
    --coalescent 0.0013151 --dates metadata.csv
```

However this corresponding `augur refine` command fails:
```
augur refine  --tree <TREE>  --alignment <ALN>    --metadata metadata.csv    \
         --output-tree <OUT_TREE>   --output-node-data <JSON>    --timetree  \
      --coalescent 0.0013151      --clock-filter-iqd 0 
```

```
156.93 TreeTime.reroot: with method or node: least-squares
 
157.04 TreeTime.reroot: rerooting will account for covariance and shared ancestry.
 
215.55 ###TreeTime.run: INITIAL ROUND
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/local/lib/python3.7/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/usr/local/lib/python3.7/site-packages/augur/refine.py", line 200, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/usr/local/lib/python3.7/site-packages/augur/refine.py", line 70, in refine
    vary_rate=vary_rate, use_covariation=covariance, **kwarks)
  File "/usr/local/lib/python3.7/site-packages/treetime/treetime.py", line 178, in run
    self.make_time_tree(**tt_kwargs)
  File "/usr/local/lib/python3.7/site-packages/treetime/clock_tree.py", line 336, in make_time_tree
    self.init_date_constraints(clock_rate=clock_rate, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/treetime/clock_tree.py", line 289, in init_date_constraints
    one_mutation=self.one_mutation, branch_length_mode=self.branch_length_mode)
  File "/usr/local/lib/python3.7/site-packages/treetime/branch_len_interpolator.py", line 39, in __init__
    grid_left = mutation_length * (1 - np.linspace(1, 0.0, n_grid_points/3)**2.0)
  File "<__array_function__ internals>", line 6, in linspace
  File "/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

**Comment by rneher** [comment]
this was fixed in treetime about a year ago. 
https://github.com/neherlab/treetime/commit/10eb15038844a3f4e803eddaa44b136d5d2088f0

recent versions should not have this problem.
