### ISSUE TITLE
`ncov` `tip_frequencies` failing with `augur` error

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#713]
**Current Behavior**  
During `tip_frequencies` rule of the `ncov` workflow, about half of 39 builds are getting an error:
```
Traceback (most recent call last):
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/frequencies.py", line 101, in run
    tip.attr = {"num_date": np.mean(dates[tip.name])}
  File "<__array_function__ internals>", line 6, in mean
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3335, in mean
    out=out, **kwargs)
  File "/scicore/home/neher/hodcroft/miniconda3/envs/nextstrain/lib/python3.6/site-packages/numpy/core/_methods.py", line 163, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

It seems like possibly there's a missing date value, but I can't find evidence of this (number of "raw_date" entries in branch_lengths file matches number of tips in the tree; all tips in `tree.nwk` end with a colon indicating a branch length number follows). 

In `frequencies` the numeric dates are [calculated directly from metadata ](https://github.com/nextstrain/augur/blob/master/augur/frequencies.py#L82) using `get_numerical_dates` from `util` ([link](https://github.com/nextstrain/augur/blob/master/augur/utils.py#L107)). 

This implies one of the dates being processed from the metadata file is returning `None` from this, however, it seems impossible this is the first time dates are parsed (`tip_frequencies` is a fairly late step in `ncov`) so I don't really get why this isn't working this time around - though perhaps a slightly different set of commands is used earlier?

**Expected behavior**  
Should not error?

**How to reproduce**  
Unsure - not sure what the difference in some builds vs others is. 

**Your environment: if running Nextstrain locally**  
 - Operating system:   Scicore linux cluster
 - Version (e.g. `auspice 2.7.0`):  augur 11.3.0

**Comment by emmahodcroft** [comment]
Apologies. Turns out there was an old file in my repository which was messing this up in a super-weird way. Basically seems like the offending sequence _used_ to have a month and day, then was updated to just have a year, but was being included because of that old data... Anyway, my bad!
