### ISSUE TITLE
TreeTime.reroot -- ERROR: unsupported rooting mechanisms or root not found

### ISSUE THREAD

**Issue by IsabelFE** [nextstrain/augur#744]
Hello,

I am new using Nextstrain and I got the following error:

```
augur refine is using TreeTime version 0.8.1

260.60	***WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF:
      	Coted_Ivoire/BKE0504-bc6/2020

260.81	***WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF:
      	Coted_Ivoire/BKE2512-bc57/2021

261.12	***WARNING: TreeAnc: 2 nodes don't have a matching sequence in the
      	alignment. POSSIBLE ERROR.

282.69	TreeTime.reroot: with method or node: Wuhan/Hu-1/2019
Traceback (most recent call last):
  File "/opt/miniconda3/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/augur/refine.py", line 206, in run
    tt = refine(tree=T, aln=aln, ref=ref, dates=dates, confidence=args.date_confidence,
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/augur/refine.py", line 42, in refine
    tt.clock_filter(reroot=reroot, n_iqd=clock_filter_iqd, plot=False) #use whatever was specified
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treetime.py", line 327, in clock_filter
    self.reroot(root='least-squares' if reroot=='best' else reroot, covariation=False, clock_rate=fixed_clock_rate)
  File "/opt/miniconda3/envs/nextstrain/lib/python3.8/site-packages/treetime/treetime.py", line 453, in reroot
    raise UnknownMethodError('TreeTime.reroot -- ERROR: unsupported rooting mechanisms or root not found')
treetime.UnknownMethodError: TreeTime.reroot -- ERROR: unsupported rooting mechanisms or root not found
Waiting at most 5 seconds for missing files.
MissingOutputException in line 684 of /Users/isabelfernandezescapa/ncov/workflow/snakemake_rules/main_workflow.smk:
Job Missing files after 5 seconds:
results/global/tree.nwk
results/global/branch_lengths.json
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 4 completed successfully, but some output files are missing. 4
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

I would appreciate any help.

Thanks 

Isabel

**Comment by rneher** [comment]
This is probably a problem related to the sequence Wuhan/Hu-1/2019 not being part of your data set or having a subtly different name. Could you check?

**Comment by IsabelFE** [comment]
Thanks @rneher, I was just about to test that when I read your message.

**Comment by IsabelFE** [comment]
It worked. Thanks!
