### ISSUE TITLE
filter: Groups are not always stable between first and second pass through metadata

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#760]
**Current Behavior**  
When grouping by columns with a maximum number of subsampled sequences requested, augur filter needs to make a first pass through metadata to count the number of records for each group, use these counts to calculate the number of sequences to sample per group to meet the given maximum sequences threshold, and then make a second pass through the metadata to sample that number of sequences per group.

In the first pass, augur counts the number of records per group in a given chunk of metadata using the `get_groups_for_subsampling` function. In the second pass, augur calls this function again, so we avoid storing the mapping of all possible strains to groups (in memory or on disk). Calling the function again and not storing group/strain mappings simplifies the code and reduces memory use at the expense of extra runtime.

However, when users group metadata by month and a record's date field is missing month information, [the get groups function randomly generates a month for that record](https://github.com/nextstrain/augur/blob/5c89570b456b29bc70377592784f6828eaef8840/augur/filter.py#L885). Because this function gets called once in the first pass and again in the second pass, augur regenerates a random month for records like this and is likely to generate a _different group_ for the same strain.

This behavior results in a `KeyError` in augur 12.1.1, where [we expect to know what all of the groups are from the first pass](https://github.com/nextstrain/augur/blob/5c89570b456b29bc70377592784f6828eaef8840/augur/filter.py#L1441-L1446) and that assumption is violated by the random month values.

For example, the following command run on the "open" ncov dataset"

```bash
augur filter \
  --metadata data/downloaded_open.tsv \
  --output-strains test.txt \
  --output-log test_log.tsv \
  --query "division == 'Washington'" \
  --group-by year month \
  --subsample-max-sequences 2000
```

Produces the following error (randomly, when random months don't match):

```python
Traceback (most recent call last):
  File "/Users/jlhudd/miniconda3/envs/test-augur/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/Users/jlhudd/miniconda3/envs/test-augur/lib/python3.7/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/jlhudd/miniconda3/envs/test-augur/lib/python3.7/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/Users/jlhudd/miniconda3/envs/test-augur/lib/python3.7/site-packages/augur/filter.py", line 1468, in run
    queues_by_group[group].add(
KeyError: (2021, (2021, 10))
```

**Expected behavior**  

[We have discussed this random month behavior internally](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1626383135353200), with the reasoning for the original behavior described as follows:

>  if people don't want to filter out ambiguous dates, but want to sample by month, we had to come up with a way to handle this (since they apparently don't want to drop them)

We should strongly consider the value of randomly generating data like this, what the actual outcomes are for the user (degree of surprise or error caused by this choice), and how common the use case is that users want to group by month but not drop samples without month information. 

If I had metadata with the following date values:

```bash
2016-01-01
2016-01
2016-02-04
2016-03-20
2016-04-10
2016-04
2016-07
2016-09
2016 # Actual date is 2016-12-01
2016 # Actual date is 2016-06-01
2016 # Actual date is 2016-01-01
```

and I asked to group strains by year and month, the current augur implementation would randomly assign months to the last three records. When I inspect the output, I would have no way of knowing why the three final records were included (that information is internal to augur filter and ephemeral). Every time I run augur filter with these data, I will get a different result (without any clear explanation for this additional randomness). Additionally, I could end up selecting a strain that was actually collected in December as part of a group for April because of the random assignment and skip another strain from April with unambiguous date information.

My recommendation is to treat missing month data in the grouping logic the same way we treat missing year: skip individual records that don't have month information and print a warning message to standard error. Ideally, we would also log the reason for a strain being dropped. My reasoning is that 1) missing month information is relatively rare (8% of GenBank records and 1% of all GISAID records) and 2) reporting missing information instead of making up data is less surprising for users.

**How to reproduce**  

Run the command shown above on the [open metadata TSV file](https://data.nextstrain.org/files/ncov/open/metadata.tsv.gz).

**Possible solution**  

One class of solutions seeks to maintain the same external behavior as previous versions of augur such that augur randomly generates missing month information during the grouping phase. These solutions would work by storing the group/strain mappings from the first pass through the metadata and using these mappings to create priority queues per group (instead of records per group counts). The number of strains will continue to grow in the future, so storing group/strain pairs in memory is not sustainable (even though it is technically a solution now). A more sustainable solution would be to write the group/strain pairs to disk in a temporary TSV file or SQL database during the first pass and then query this external information during the second pass.

Another class of solution would change the external behavior to an arguably less surprising approach of skipping strains with missing month information when trying to group by month (technically a breaking change, warranting a new major release). A specific solution would be to apply [the logic used to skip strains with missing years](https://github.com/nextstrain/augur/blob/5c89570b456b29bc70377592784f6828eaef8840/augur/filter.py#L878-L880) to strains with missing months. This solution would require 3 lines of code and would produce more stable group output. Alternately, we could implicitly add a filter to exclude ambiguous dates by year or month when the user requests groups by either year and month. This solution would have the effect of logging why strains were excluding from the analysis, but it could produce surprising output (e.g., "I didn't ask to exclude ambiguous dates...").

**Comment by huddlej** [comment]
After chatting with @emmahodcroft and @rneher about this, we can to the following conclusions:

 - Randomly assigned months attempt to address the case where high-quality sampling is heavily biased toward one geographic location while other locations have fewer samples with more ambiguity about date (e.g., Enterovirus D68 as the US continues to sequence more than other countries). This solution was in one of the first augur commits (maybe not originally intended to be a long-term solution).
 - We agreed that randomly assigning months isn’t an acceptable long-term solution to the problem. We should skip strains with missing months, but we need to alert the user that this is happening. Ideally, we would log strains that have been skipped to the --output-log , too. We also need to make a major release of augur, to call out this change in behavior.
 - One could potentially address the biased sampling problem by calling augur filter multiple times with different parameters (like we subsample for SARS-CoV-2). We should document how to do this in a how-to guide in the main Nextstrain docs perhaps using Enterovirus D68 as an initial example. Generally, we need better documentation about how to subsample under different scenarios anyway.
 - We assume that users know their data well enough to know how they want to subsample dates, etc. For some researchers (e.g., our team, folks studying HIV where year-only dates are common, etc.), this is a good assumption.
 - We shouldn’t try to make augur filter handle every possible edge case. Instead, we should encourage users to better understand their own data and how to properly subsample it (see need for docs above).

Based on this discussion, I'll plan to address this issue with the following steps:

 - [ ] Add a functional test that captures the current issue
 - [ ] Update `get_groups_for_subsampling` to skip strains with missing months and store a list of skipped strains and reasons
 - [ ] Update the first pass through the metadata to count and log the number of strains skipped during group-by and then print these counts in the final report
 - [ ] Release this change in Augur 13.0.0
 - [ ] Create an issue in the Nextstrain docs repo to create a how-to guide for subsampling
