### ISSUE TITLE
augur translate: ValueError("No records found in handle")

### ISSUE THREAD

**Issue by lasupernova** [nextstrain/augur#764]
Hi everyone, I have been running several analyses and I am able to create the correct json output file.
However, the augur trasnlate step is not working for me. All precious steps ran just fine and I have all files required for augur trasnlate in the results folder (nt_muts.json is in the folder and looks ok when checking with 'head').

I ran the following:

`augur translate --tree results/tree.nwk --ancestral-sequences results/nt_muts.json --reference-sequence data/reference.fasta --output-node-data results/aa_muts.json`

I get this error:

```
Traceback (most recent call last):
File "usr/bin/anaconda3/envs/nextstrain/bin/augur", line 10, in <module>
   sys.exit(main())
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/translate.py", line 350, in run
   features = load_features(args.reference_sequence, genes)
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/augur/utils.py", line 273, in load_features
   for feat in SeqIO.read(reference, 'genbank').features:
  File "/usr/bin/anaconda3/envs/nextstrain/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 748, in read
  raise ValueError("No records found in handle")
```

Has anyone encountered this error and can help? Thanks in advance :)

**Comment by jameshadfield** [comment]
Hi @lasupernova - the reference sequence passed in needs to be a GenBank or GFF file containing details about the genes to translate (in your command you are passing in a fasta file, which will not contain this information). For example, in our ncov workflow we run `augur translate ... --reference-sequence defaults/reference_seq.gb`. 

The exact format of these files can be a bit tricky. For examples, see the reference files we are using for [ncov](https://github.com/nextstrain/ncov/blob/master/defaults/reference_seq.gb) and [zika](https://github.com/nextstrain/zika/blob/master/config/zika_reference.gb).

**Comment by genehack** [comment]
I am closing this issue. It has been untouched for over three years, and I suspect James's answer was sufficient to resolve the issue.

We're trying to get a good handle on our open issues and PRs, so that they can serve as a reliable backlog of things we actually will work on. If you are still seeing this issue and are confident we should re-examine it, please reopen it and explain why, thank.
