### ISSUE TITLE
Ancestral traits reconstruction produces UnicodeEncodeError 

### ISSUE THREAD

**Issue by mtw** [nextstrain/augur#765]
`augur traits` produces a UnicodeEncodeError 

     Traceback (most recent call last):
     File "/Users/mtw/miniconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/traits.py", line 172, in run
    weights=weight_dict[column])
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/traits.py", line 70, in mugration_inference
    sampling_bias_correction=sampling_bias_correction, weights=weights)
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/treetime/wrappers.py", line 794, in reconstruct_discrete_traits
    for n in treeanc.tree.get_terminals()]
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/treetime/wrappers.py", line 794, in <listcomp>
    for n in treeanc.tree.get_terminals()]
     File "/Users/mtw/miniconda3/envs/nextstrain/lib/python3.6/site-packages/Bio/Seq.py", line 1725, in __init__
    self._data = bytes(data, encoding="ASCII")
    UnicodeEncodeError: 'ascii' codec can't encode character '\x8c' in position 0: ordinal not in range(128)

A similar issue has been reported in #559, however, I am not sure whether the current issue is related. Any ideas on how to resolve this are highly appreciated.

This is my environment:
   >python: 3.6.13
   Biopython: 1.79
    augur: 11.3.0

**Comment by tsibley** [comment]
@mtw Thanks for the detailed bug report. This is a bad interaction between TreeTime and BioPython 1.79, because the latter switched `Bio.Seq` storage from Unicode strings to ASCII bytes ([changelog](https://github.com/biopython/biopython/blob/master/NEWS.rst#3-june-2021-biopython-179), [PR](https://github.com/biopython/biopython/pull/3333)) and TreeTime constructs a trait alphabet that can exceed ASCII's range (as described in #559).

The best solution is probably to update TreeTime to change how it constructs a trait alphabet and passes it to `Bio.Seq`. In the meantime, as a workaround, downgrading BioPython to 1.76 should fix your issue. (1.78 and 1.77 have known bugs that affect other parts of TreeTime.)

Separately, Augur's dependency declarations ([setup.py](https://github.com/nextstrain/augur/blob/e7728559417cd98a426bf5cb99a257b63fdc705f/setup.py#L51), [bioconda](https://github.com/bioconda/bioconda-recipes/blob/658b3b3697f218223df42d7f19ce5b916788e89a/recipes/augur/meta.yaml#L26)) already constrain on BioPython <=1.76, so I'm curious if you could share more about how your environment was installed? If something's not respecting those dependency declarations, it'd be good to identify and address it.

/cc @huddlej @rneher

**Comment by rneher** [comment]
I have released a new version of treetime to address this (bypassing Bio.Seq for the mugration analysis).
https://github.com/neherlab/treetime/releases/tag/v0.8.3.1
is also on pypi. 

if the problem persists, please let me know!
