### ISSUE TITLE
BUG: augur filter does not allow `year` column in metadata, crashes with `ValueError`

### ISSUE THREAD

**Issue by LauraU123** [nextstrain/augur#871]
### Current Behavior
When the `metadata.tsv` contains a column named `year`, `augur filter` throws a cryptic `ValueError: cannot reindex on an axis with duplicate labels`

### Expected behavior
The user is allowed to have a column named `year` in addition to `date`, or at least this prohibition is documented

### How to reproduce
Steps to reproduce the current behavior:
1. Create metadata with columns `year`, and `date` among others, see text file
2. Run `augur filter` command:
```
augur filter   --metadata data/b.txt    --group-by country year month   --sequences-per-group 20 --output-strains throwaway.txt  --min-date 2012
```
3. See error

[b.txt](https://github.com/nextstrain/augur/files/8288031/b.txt)

Stacktrace:
```
(nextstrain) laura@laura-ThinkPad-X1-Carbon-Gen-9:~/rsv$ augur filter   --metadata data/b.txt    --group-by country year month   --sequences-per-group 20 --output-strains throwaway.txt  --min-date 2012
/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/filter.py:930: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  df_skip = metadata[metadata['year'].isnull()]
Traceback (most recent call last):
  File "/home/laura/miniconda3/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/filter.py", line 1400, in run
    group_by_strain, skipped_strains = get_groups_for_subsampling(
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/filter.py", line 930, in get_groups_for_subsampling
    df_skip = metadata[metadata['year'].isnull()]
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/frame.py", line 3492, in __getitem__
    return self.where(key)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/frame.py", line 10949, in where
    return super().where(cond, other, inplace, axis, level, errors, try_cast)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/generic.py", line 9318, in where
    return self._where(cond, other, inplace, axis, level, errors=errors)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/generic.py", line 9081, in _where
    cond = cond.reindex(self._info_axis, axis=self._info_axis_number, copy=False)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/frame.py", line 4798, in reindex
    return super().reindex(**kwargs)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/generic.py", line 4974, in reindex
    return self._reindex_axes(
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/frame.py", line 4611, in _reindex_axes
    frame = frame._reindex_columns(
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/frame.py", line 4656, in _reindex_columns
    return self._reindex_with_indexers(
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/generic.py", line 5040, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 679, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "/home/laura/miniconda3/envs/nextstrain/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 4107, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

### Your environment: if browsing Nextstrain online
Augur 14.0.0

**Comment by victorlin** [comment]
Supporting custom `year` `month` `day` columns seems like something we should do, but need to clearly define how to support it.

Currently, when using `augur filter --group-by year month`, this is assuming the generated columns, and it's likely that many users' workflows depend on this behavior. If we rename our `year` `month` `day` columns, it will break all those workflows.

One approach: keep current behavior and rename the generated columns only if necessary. For example, if a custom `year` is provided, that will "override" the generated `year` column. If users wish to use the generated column, they should use a special prefix `_augur_filter_year` or something.

Open to other suggestions here.

**Comment by jameshadfield** [comment]
It's somewhat common for bioinformaticians to encode dates via three columns, "year", "month", "day" (e.g. [microreact docs](https://docs.microreact.org/instructions/creating-a-microreact-project/metadata-column-types#optional-columns)). It'd be great to support this.

**Comment by emmahodcroft** [comment]
@victorlin - not sure I follow. I think the columns we generate are purely internal - we don't export them afterwards. They're just for us to split up to allow us to do the `group-by` internally - right?
So, I don't think any user is expecting these columns to be there, or that we'll use their columns, or even that their columns would be compatible with our needs (we need numerical months, but a user could have a column called 'months' that could be June, July etc).

I can imagine a use-case where if a user _doesn't_ have a `date` column (for example, a microreact export with format @jameshadfield mentions), we might want to use `year` `month` `day` instead -- but they will need a `date` column for many other functions in `augur`, so it also seems like supporting this just for `filter` is kind of weird (though perhaps if people do just use `filter` alone, then worth supporting?).

But apart from having a missing `date` column, I don't think we can assume that users will expect a `year` column to be used for filtering, for example - I certainly wouldn't. (For EV-D68 data, for example, I can totally see myself making a `year` column and filling it with `odd` and `even` to designate the offset biennial outbreak patterns in different regions.) I think we should handle this like any other custom user column, outside of some special cases.

**Comment by victorlin** [comment]
> the columns we generate are purely internal - we don't export them afterwards

@emmahodcroft hmm, not exactly. They are exported for usage in this example:

```sh
echo -e 'strain\tdate
SEQ1\t2021-01-01
SEQ2\t2021-01-02
SEQ3\t2022-01-01
SEQ4\t2022-01-02
SEQ5\t2022-02-02
' > metadata.tsv

augur filter \
  --metadata metadata.tsv \
  --group-by year month \
  --sequences-per-group 1 \
  --output-strains filtered.txt
# 3 strains passed all filters
```

So if a `year` column is added with values `odd`/`even`, the same `--group-by year month` breaks:

```sh
echo -e 'strain\tdate\tyear
SEQ1\t2021-01-01\todd
SEQ2\t2021-01-02\todd
SEQ3\t2022-01-01\teven
SEQ4\t2022-01-02\teven
SEQ5\t2022-02-02\teven
' > metadata.tsv

augur filter \
  --metadata metadata.tsv \
  --group-by year month \
  --sequences-per-group 1 \
  --output-strains filtered.txt
# ValueError: cannot reindex on an axis with duplicate labels
```

We could support the original functionality with a prefix on generated columns `_augur_filter_`, like so:

```sh
augur filter \
  --metadata metadata.tsv \
  --group-by _augur_filter_year _augur_filter_month \
  --sequences-per-group 1 \
  --output-strains filtered.txt
# 3 strains passed all filters
```

Or the original `year` column could be used like so:

```sh
augur filter \
  --metadata metadata.tsv \
  --group-by year \
  --sequences-per-group 1 \
  --output-strains filtered.txt
# 2 strains passed all filters
```

**Comment by huddlej** [comment]
Following this and [the Slack conversation around this](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1647540620020169), I wonder why we can't prefer user-defined columns over the generated columns when there is a conflict.

Building on @victorlin's example data and command above, I imagine the following behavior:

```
echo -e 'strain\tdate\tyear
SEQ1\t2021-01-01\todd
SEQ2\t2021-01-02\todd
SEQ3\t2022-01-01\teven
SEQ4\t2022-01-02\teven
SEQ5\t2022-02-02\teven
' > metadata.tsv

# Groups by predefined "year" column from the user ("odd" and "even" values)
# and groups by the "month" column generated from the date.
augur filter \
  --metadata metadata.tsv \
  --group-by year month \
  --sequences-per-group 1 \
  --output-metadata filtered.tsv
```

In this example, as in @LauraU123's example, the user has knowingly defined a column called `year` and asked Augur to group by that column. The user has not defined a column called `month`, but they would like Augur to calculate the month from their `date` column. This behavior has the potential disadvantage of hiding the generated `year` column from the user when that's what they really want.

Alternately, clearly exposing the generated nature of the year and month columns seems cleaner in the long-run. Between choices proposed like `--group-by _augur_filter_year` and `--group-by year(date)`, the syntax of the latter might be clearer. I'd worry about going too far down the road of implementing a SQL-style query syntax for grouping, though. If we could push more for early sanitizing of metadata to have expected field names instead, we could keep augur filter simpler.

**Comment by huddlej** [comment]
Maybe it's worth clarifying more directly, though. :)

@LauraU123: Do you expect augur filter to group by the existing `country` and `year` columns in your metadata but to generate a `month` column from your `date` column for the final grouping? In other words, were you relying on the behavior of these generated date columns or are those a bit of a surprise?

**Comment by tsibley** [comment]
@victorlin The important thing is that the external interface of `--group-by {year | month | day}` keeps working when those columns (the internal interface) don't exist. Internally, it doesn't really matter what we call those virtual/generated columns.

**Comment by emmahodcroft** [comment]
Yes sorry - to clarify my own comment, what I was saying is that I can imagine myself adding an `odd`/`even` `year` column for entirely my own purposes (like coloring or something) - I would still be expecting `filter` to act on `date` when I ask for it to `group-by year month`. For me (though for a naive user it might be different) I would be surprised if it tried to act on my `year` column - I just happened to create a column called year, but in my mind, it's unrelated from `date` or `filter` in any way.

I think we want to be careful about trying to support every use-case we can imagine - we'll never get them all and we run a risk of making things super-complicated. I think adding a user-defined date column is a great middle-step - if you do want to filter by alternative dates, you can do this with John's PR, but it's very explicit, so no need to figure out expectations of whether a user meant for `year` to be used by filter or not.

>They are exposed for usage in this example

@victorlin there might be a difference in interpretation here, which might be worth exploring - but certainly to me, my implicit understanding has always been that `--group-by year month` were referring to the parts of the `date` object, and not anything that could be specified more specifically -- since without inspecting the code you wouldn't even know that we actually create columns by these names to do this filtering.

**Comment by ammaraziz** [comment]
Jumping in here as I have experienced the same issue/error. First go at using `filter` subcommand (and not reading the docs carefully), I had manually created a `year` `month` column. When the error was produced because I was grouping by `year` and `month`, I read the docs and the error made more sense. 

I personally have never thought to use a custom year and the virtual month. I've assumed when parsing the date field the `month` and `year` virtual fields are added to the dataframe. Therefore having a custom year and month causes conflict.

I have a few suggestions that I think will help the situation:
1. In the docs highlight+document this very useful feature of augur https://docs.nextstrain.org/projects/augur/en/stable
/faq/metadata.html

2. Currently it is only documented in the `augur filter` help for `--group-by` option. The explanation is also confusing:

>... two virtual fields, "month" and "year", are supported if they don't already exist as real fields but a "date" field does exist.

This is essentially saying "we create year and month for you if they don't exist". The reality it conflicts with the virtual fields. This should be changed to reflect the possible conflict or provide a warning. At least for the time being until mixing of user defined and virtual fields is supported.

3. `argparse` has the `epilogue` option to allow a message after the help docs. Adding an extra note here could further highlight the virtual fields and reiterating possible conflict.

4. if the metadata contains `year` or `month` columns, warn the user that these will be ignored in favor of the virtual fields and recommend to rename the columns to upper case. 
Thanks,

Ammar
