### ISSUE TITLE
Augur clades not working properly

### ISSUE THREAD

**Issue by AnunayS** [nextstrain/augur#894]
I have been trying to use augur to draw a phylogenetic tree.

the command I am using is as follows: 

augur clades --tree Omicron_refined_tree.nwk --mutations Omicron_aa_muts.json ncov_nt_muts.json --clades clades.tsv --output-node-data Omicron_clades.json

The error message which I get is as follows:

Validating schema of 'Omicron_aa_muts.json'...
Traceback (most recent call last):
  File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'gene'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sequencing/miniconda3/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/clades.py", line 268, in run
    clade_designations = read_in_clade_definitions(args.clades)
  File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/clades.py", line 50, in read_in_clade_definitions
    clade_inheritance_rows = df[df['gene'] == 'clade']
  File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'gene'

Can some one please tell me what am I doing wrong. All the previous steps are completed successfully.

Thank you.

**Comment by corneliusroemer** [comment]
I can't reproduce this as is. Could you please share your `clades.tsv` file? 

The easiest explanation would be that it doesn't have the right header? Or maybe you use spaces instead of tabs?

**Comment by AnunayS** [comment]
Thanks a lot.
It was a problem with the header itself.
It was space+tab separated.

**Comment by corneliusroemer** [comment]
Thanks for confirming!

Makes me think the problem is that the error message is not helpful enough.

We should validate input conforms to expectation and provide helpful error.

Will think about opening a new issue for this. Thanks for reporting -
wouldn't have got the idea otherwise!
