### ISSUE TITLE
ENH: Validate clades.tsv file and provide helpful error message if it doesn't conform to requirements

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#897]
It would be good to explicitly validate the clades.tsv file and give a helpful error message if it doesn't conform to expectations.

This would help users like this one, who opened issue https://github.com/nextstrain/augur/issues/894

> the command I am using is as follows:
> 
> augur clades --tree Omicron_refined_tree.nwk --mutations Omicron_aa_muts.json ncov_nt_muts.json --clades clades.tsv --output-node-data Omicron_clades.json
> 
> The error message which I get is as follows:
> 
> Validating schema of 'Omicron_aa_muts.json'... Traceback (most recent call last): File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc return self._engine.get_loc(casted_key) File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'gene'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/sequencing/miniconda3/bin/augur", line 8, in sys.exit(main()) File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/**main**.py", line 10, in main return augur.run( argv[1:] ) File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/**init**.py", line 75, in run return args.**command**.run(args) File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/clades.py", line 268, in run clade_designations = read_in_clade_definitions(args.clades) File "/home/sequencing/miniconda3/lib/python3.8/site-packages/augur/clades.py", line 50, in read_in_clade_definitions clade_inheritance_rows = df[df['gene'] == 'clade'] File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3458, in **getitem** indexer = self.columns.get_loc(key) File "/home/sequencing/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc raise KeyError(key) from err KeyError: 'gene'
> 
> Can some one please tell me what am I doing wrong. All the previous steps are completed successfully.

**Comment by huddlej** [comment]
Related to https://github.com/nextstrain/augur/issues/642

**Comment by jameshadfield** [comment]
See also https://github.com/nextstrain/augur/issues/735

**Comment by jameshadfield** [comment]
Augur clades neds quite a bit of work under the hood to make it more robust and to consider & document edge-cases in behavior. I wrote a bit about this at https://github.com/nextstrain/augur/issues/735 - including comments on the lack of validation we do (it's worse than lack of validation 😬 ). I think we'd be better served by a major lift on the code rather than a small patch over this particular bug.
