### ISSUE TITLE
Cryptic error message in Augur filter: `KeyError: ('_dummy',)`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#932]
### Current Behavior
When I run `augur filter`, asking for `--group-by year` but `year` is missing from metadata, I get the following stack trace which doesn't provide much of a clue to the user what is wrong.

Trace back:

```
augur filter             --sequences data/h1n1pdm_ha_sequences.fasta             --metadata data/h1n1pdm_ha_metadata.tsv             --include data/includes_h1n1pdm_ha_CY121680.tsv             --include-where EPI_ISL=EPI1583287             --min-date 2016 --probabilistic-sampling --group-by year --subsample-max-sequences 1500             --output build/h1n1pdm/ha/CY121680/subsample_raw.fasta             --output-strains build/h1n1pdm/ha/CY121680/subsample_raw.txt
Note: You did not provide a sequence index, so Augur will generate one. You can generate your own index ahead of time with `augur index` and pass it with `augur filter --sequence-index`.
WARNING: The specified group-by categories (['year']) were not found. No sequences-per-group sampling will be done. Note that using 'year' or 'year month' requires a column called 'date'.
Sampling at 1500 per group.
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/filter.py", line 1544, in run
    queues_by_group[group].add(
KeyError: ('_dummy',)
```

### Expected behavior
The error message is wrapped and bubbled up in something more user friendly with actionable points. I guess the warning is related, but then this should be an error not a warning.

### How to reproduce
I'll send the files internally on request, these are GISAID sequences.

- Version: augur 15.0.2 via bioconda

**Comment by victorlin** [comment]
Here's a minimal reproducible example:

```sh
cat > metadata.tsv << ~~
strain	col
SEQ1	a
SEQ2	b
~~

augur filter \
--metadata metadata.tsv \
--group-by year \
--subsample-max-sequences 1 \
--output-strains out.txt
```
