### ISSUE TITLE
BUG in mask: empty (header only) .bed file causes unhandled error

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#945]
### Current Behavior
When the `.bed` file passed to `mask` contains just a header and nothing to mask, an unhandled error is thrown.

### Expected behavior
Empty, header only `.bed` files are accepted and cause simply no masking.

### How to reproduce
Run `augur mask --sequences results/global/aligned.fasta --mask config/mask.bed --mask-from-beginning 7000 --mask-from-end 7000 --output results/global/masked.fasta`
with a header onl `.bed` file.

Augur 15.0.2

Stacktrace:
```
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1113, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('O') to dtype('int64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/utils.py", line 678, in read_bed_file
    bed = pd.read_csv(bed_file, sep='\t', header=None, usecols=[1,2],
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 883, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1026, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1119, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: invalid literal for int() with base 10: 'ChromStart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/mask.py", line 215, in run
    mask_sites.update(load_mask_sites(args.mask_file))
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/utils.py", line 734, in load_mask_sites
    mask_sites = read_bed_file(mask_file)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/utils.py", line 682, in read_bed_file
    bed = pd.read_csv(bed_file, sep='\t', header=None, usecols=[1,2],
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by corneliusroemer** [comment]
Also, an empty file should be accepted as well. But currently it throws an error, so not even a simple workaround exists :/ 
```
ERROR: config/mask.bed is an empty file.
```

**Comment by victorlin** [comment]
Should update code to catch this error and print the message above.

**Comment by tsibley** [comment]
[Canonical BED format specification](https://genome.ucsc.edu/FAQ/FAQformat.html#format1)

**Comment by corneliusroemer** [comment]
@tsibley are you saying an empty bed file is not legal? I couldn't find out whether that's the case glancing through the spec. Do you know?

**Comment by jameshadfield** [comment]
Empty `bed` files should be fine. Nothing on the specification seems to indicate that it's not, and the following works fine:

```
$ touch empty
$ bedtools sort -i empty 
$ echo $?
0
```

**Comment by tsibley** [comment]
> are you saying an empty bed file is not legal?

No, not saying that. Was just linking to the spec for reference. Sorry I didn't include more context.

**Comment by tsibley** [comment]
Keeping this comment descriptive rather than prescriptive (at least for the moment).

There's two separate things here:

1. BED files with no regions/data lines ("empty")
2. BED files with a header line

which sometimes occur together and sometimes occur separately. This issue is about both 1 with 2 (just a header) and 1 without 2 (the zero-byte BED file).

Regardless of how Augur handles zero-byte BED files, there's no standard header for BED files, c.f. the spec above and `bedtools` behaviour:

```
$ cat config/mask.bed 
Chrom	ChromStart	ChromEnd	locus tag	Comment
chr	6400	7500		very diverse region
chr	133050	133250		indel variation and long homopolymers

$ bedtools sort -i config/mask.bed 
Unexpected file format.  Please use tab-delimited BED, GFF, or VCF. Perhaps you have non-integer starts or ends at line 1?
[1]

$ bedtools sort -i <(tail -n +2 config/mask.bed)
chr	6400	7500		very diverse region
chr	133050	133250		indel variation and long homopolymers
```

although `bedtools` does (at least) ignore lines starting with `#`. This applies to all lines though, not just the first line.

Augur's `read_bed_file()` currently skips the first line if there's a parsing failure and tries again, which handles ad-hoc headers but will also mask other errors in the first line.

**Comment by genehack** [comment]
> Regardless of how Augur handles zero-byte BED files, there's no standard header for BED files, c.f. the spec above and `bedtools` behaviour:

This, I believe, is incorrect. The [UCSC BED format page](https://genome.ucsc.edu/FAQ/FAQformat.html#format1): says:

> Please note that only in custom tracks can the first lines of the file consist of header lines, which begin with the word "browser" or "track" to assist the browser in the display and interpretation of the lines of BED data following the headers.

and `bedtools`, while it (properly!) chokes on a line starting with "Chrom", is perfectly happy with lines starting with "browser" or "track":

```
> cat bad_mask.bed
───────┬────────────────────────────────────────────────────────────────────────────────────
       │ File: bad_mask.bed
───────┼────────────────────────────────────────────────────────────────────────────────────
   1   │ Chrom   ChromStart  ChromEnd    locus tag   Comment
   2   │ chr 133050  133250      indel variation and long homopolymers
   3   │ chr 136500  136600      indel variation and long homopolymers
   4   │ chr 140050  140250      indel variation and long repetitive elements
   5   │ chr 146750  147000      indel variation and long repetitive elements
   6   │ chr 150500  150650      indel variation and long repetitive elements
   7   │ chr 169250  169500      indel variation and long repetitive elements
   8   │ chr 169700  169800      indel variation and long repetitive elements
   9   │ chr 173150  173350      indel variation and long repetitive elements
  10   │ chr 179000  179300      indel variation and long repetitive elements
───────┴────────────────────────────────────────────────────────────────────────────────────

> bedtools sort -i ./bad_mask.bed                                                                        
Unexpected file format.  Please use tab-delimited BED, GFF, or VCF. Perhaps you have non-integer starts or ends at line 1?

> cat mask.bed                                                                                           
───────┬────────────────────────────────────────────────────────────────────────────────────
       │ File: mask.bed
───────┴────────────────────────────────────────────────────────────────────────────────────

   1   │ track   ChromStart  ChromEnd    locus tag   Comment
   2   │ browser foo bar baz
   3   │ chr 133050  133250      indel variation and long homopolymers
   4   │ chr 136500  136600      indel variation and long homopolymers
   5   │ chr 140050  140250      indel variation and long repetitive elements
   6   │ chr 146750  147000      indel variation and long repetitive elements
   7   │ chr 150500  150650      indel variation and long repetitive elements
   8   │ chr 169250  169500      indel variation and long repetitive elements
   9   │ chr 169700  169800      indel variation and long repetitive elements
  10   │ chr 173150  173350      indel variation and long repetitive elements
  11   │ chr 179000  179300      indel variation and long repetitive elements
───────┴────────────────────────────────────────────────────────────────────────────────────

> bedtools sort -i ./mask.bed                                                                            
chr     133050  133250          indel variation and long homopolymers
chr     136500  136600          indel variation and long homopolymers
chr     140050  140250          indel variation and long repetitive elements
chr     146750  147000          indel variation and long repetitive elements
chr     150500  150650          indel variation and long repetitive elements
chr     169250  169500          indel variation and long repetitive elements
chr     169700  169800          indel variation and long repetitive elements
chr     173150  173350          indel variation and long repetitive elements
chr     179000  179300          indel variation and long repetitive elements
```

I think the issue here is that _augur_ has been incorrectly allowing BED files with an initial invalid header line to be parsable.

**Comment by genehack** [comment]
Further, `bedtools` seems to allow lines starting with `#` to occur anywhere, and to _not_ require all the `chrom` values to match:

```
> cat mask.bed    
───────┬──────────────────────────────────────────────────────────────────────────────────────
       │ File: mask.bed
───────┼──────────────────────────────────────────────────────────────────────────────────────
   1   │ track   ChromStart  ChromEnd    locus tag   Comment
   2   │ browser foo bar baz
   3   │ chr 133050  133250      indel variation and long homopolymers
   4   │ chr 136500  136600      indel variation and long homopolymers
   5   │ # chr   140050  140250      indel variation and long repetitive elements
   6   │ chr 146750  147000      indel variation and long repetitive elements
   7   │ chr 150500  150650      indel variation and long repetitive elements
   8   │ chr 169250  169500      indel variation and long repetitive elements
   9   │ chr 169700  169800      indel variation and long repetitive elements
  10   │ chr 173150  173350      indel variation and long repetitive elements
  11   │ chr2    179000  179300      indel variation and long repetitive elements
───────┼──────────────────────────────────────────────────────────────────────────────────────

> bedtools sort -i ./mask.bed                                                                            
chr     133050  133250          indel variation and long homopolymers
chr     136500  136600          indel variation and long homopolymers
chr     146750  147000          indel variation and long repetitive elements
chr     150500  150650          indel variation and long repetitive elements
chr     169250  169500          indel variation and long repetitive elements
chr     169700  169800          indel variation and long repetitive elements
chr     173150  173350          indel variation and long repetitive elements
chr2    179000  179300          indel variation and long repetitive elements
```

**Comment by genehack** [comment]
Summarizing dev-chat feedback on the above:

* Continue to allow header lines that start with `chrom` (I will probably convert the header line matching to do a case-insensitive comparison, so as to cover `chrom`, `Chrom`, `CHROM`, etc.) 

I'm also going to allow lines starting `#` to be skipped anywhere. 

Further feedback is welcome; will let this sit until next week before picking it back up.
